### ISSUE TITLE
اصلاح ترجمه ها و تایپو ها

### ISSUE THREAD

**Issue by emadbagheri96** [mohammadr3z/persian-elementor#2]
با سلام و خسته نباشید و آفرین به کار قشنگتون
یک سری نکات ریز هست بنده عرض میکنم
`نمایش در موبایل` به صورت `نماشی در موبایل` تایپ شده
`تگ های داینامیک` میتونه به `برچسب های پویا` تغییر کنه
`سایز` به `اندازه`
در قسمت ویژگی ها، در متن راهنما، قسمتی که کلید مقدار هست، کلمه `مقدار` به صورت `مقدر` تایپ شده
`فیلیپ جعبه` میتونه به `چرخش جعبه` ترجمه شه
`منو` به `فهرست` ترجمه شه
در تنظیمات المان ویدیو، دکمه کنترل پخش کننده، `نمایش دادن` ترجمه شده که به علت طولانی بودن در دو خط نشون داده میشه و میتونه اختصارا `نمایش` نوشته شه
خود وردپرس `پست` رو به `نوشته` ترجمه کرده و شما هم میتونین اینکار رو کنین
در صفحه پلاگین ها که همه افزونه ها قابل مشاهده هستن، میتونین رو به روی خود افزونه، لینک به تنظیمات خود افزونه رو اضافه کنید
توی فونت های هم جای خالی ایران سنس حس میشه

**Comment by mohammadr3z** [comment]
خیلی ممنون از اصلاحیات حتما بررسی و در نسخه جدید ارائه می شود.
فونت هایی مانند ایران سنس به دلیل اینکه تجاری بوده و دارای لایسنس، در نسخه رایگان فارسی ساز قرار نگرفته است. ولی می تونید در نسخه پریمیوم این فارسی ساز، فونت های تجاری را به همراه لایسنس قانونی نیز استفاده کنید.
 لینک نسخه پولی افزونه: http://bit.ly/persian-elementor-pro
